--UPDATE public.event SET "trial_user_id" = '1', "trial_role_id" = '1' WHERE "id" = '1';
--UPDATE public.event SET "trial_user_id" = '2', "trial_role_id" = '2' WHERE "id" = '3';
--UPDATE public.event SET "trial_user_id" = '3', "trial_role_id" = '6' WHERE "id" = '4';
--UPDATE public.event SET "trial_user_id" = '4', "trial_role_id" = '6' WHERE "id" = '6';