# ===================================================================
# Authentication & Authorization Configuration
# ===================================================================

security:

  # HTTP session-related settings
  session:

    # A strategy for mapping HTTP request and responses to a Session (supported values: 'cookie', 'header')
    strategy: header

    # Name of the cookie used to hold session id
    cookieName: ppsid

    # Maximum age of the cookie (special value '-1' signals to delete the cookie when the browser is closed)
    cookieMaxAge: -1

    # Name of the HTTP header used to hold authentication token
    headerName: X-Auth-Token